version: '3'
services:
  datadog:
    image: 'datadog/agent:7.31.1'
    environment:
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.team":"team",trible:"trible"}
      - DD_TAGS='env:staging'
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=datadog
    ports:
      - 127.0.0.1:8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "agent"}]'
      com.datadoghq.tags.env: 'staging'
      com.datadoghq.tags.service: 'datadog'
      com.datadoghq.tags.version: '7.31.1'
      my.custom.label.team: 'confiabilidade'
      my.custom.label.trible: 'platform'
  
  api-challenge:
    build: .
    depends_on:
      - datadog
    environment:
      - DD_SERVICE=discounts-service
      - DD_ENV=intro-to-logs
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1.0
      - DD_AGENT_HOST=datadog
    ports:
      - "3333:3333"
      - "3000:3000"
    labels:
      com.datadoghq.ad.logs: '[{"source": "api-challenge", "service": "api-challenge"}]'
